default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch('RDS_DB_NAME') { 'kimer' } %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  <<: *default
  database: <%= ENV.fetch('RDS_DB_NAME') { 'pddma1022009' } %>

test:
  <<: *default
  database: <%= ENV.fetch('RDS_DB_NAME') { 'pddma1022009_test' } %>

production:
  <<: *default
